### PR TITLE
Make Compatible with PyPi/pip install

### PR DESCRIPTION
**Pull request by jimjkelly**
Added MANIFEST.in file

Update README and convert to RST

Create setup.py

Add LICENSE.txt

Change so that main py file is in proper location, and add **init** there

Move README to rst to properly display on GitHub

Fix rst markup issue

Added requirement for requests dependency

Add encoding to setup.py

### CODE REVIEW

**Comment by yarian** [comment]
Hey Jim, 

Thanks for bringing this up. Definitely a good thing to do. Let me learn more about it and I'll get back to you. Quick question, why does it have to be an RST readme? Is that just a pypi requirement?

**Comment by jimjkelly** [comment]
Last I checked it was a requirement of pypi.  I'm more of a fan of markdown myself.  :/

**Comment by awonak** [comment]
Bump on this issue. Even if you do not want to submit it to the pypi directory, it's useful to have a setup.py to be able to pip install directly from the git repo. For example, with @jimjkelly's repo I can install from github with the following command:
`pip install git+ssh://git@github.com/jimjkelly/brewerydb@task/makepipinstallable`

One comment, the MANIFEST.in references directories and files that do not exist. Just delete that second line since there aren't any docs.

**Comment by jimjkelly** [comment]
Bleh I realized that I deleted my fork during some spring cleaning, and forgot I had the pull request here. So pip installing directly from my fork will no longer work. 

Anyone tending the shop here? Any interest in the PR?

**Comment by jimjkelly** [comment]
Also, removed by absurdly long original title, the full thing saved here for posterity:

> I'm not sure if this is something you are interested in, but this should be all that is necessary to make the package ready to distribute via pypi.  All you should need to do is follow the rest of the instructions here - http://guide.python-distribute.org

**Pull request closed without merging**
